### ISSUE TITLE
Software crashes upon pressing "settings"

### ISSUE THREAD

**Issue by shambala12** [Tumppi066/Euro-Truck-Simulator-2-Lane-Assist#8] opened 2022-08-14 11:30 UTC
I followed the installation video, step by step and got the software installed. Upon launch, I press settings where the whole software crashes. I get the message "NameError: name 'wheel' is not defined.
![Screenshot_1](https://user-images.githubusercontent.com/13783966/184534654-e3fe2026-fd99-436b-907e-f4e8003a4561.png)

**Comment by Tumppi066** [comment] 2022-08-14 14:05
Sorry for the late response, we were at our summer cottage and it doesn't have an internet connection.

Unfortunately you must have a controller or wheel to use the app. If you have one, then please plug it in. If you don't have a controller then I suggest looking at this application, note that I have not used it myself : https://youtu.be/_UHNavRGav4 

If this fixes your issue then please close it :)

**Comment by shambala12** [comment] 2022-08-15 12:09
Ah right, I thought the virtual controller was a way of bypassing the need for a physical controller. Unfortunately that application does not work on windows 11 according to the Dev so guess I'm out of options for now. Thanks anyway and enjoy your holiday

**Closed** 2022-08-15 12:09 UTC

**Comment by Tumppi066** [comment] 2022-08-15 12:47
Ah that's too bad, well if the problem is vjoy (I had thought about using it myself too, just found a better virtual controller) then I succesfully installed this version of [vjoy](https://github.com/jshafer817/vJoy/releases) (github.com) on windows 11.
